(() => {
  'use strict';
  const Store=PortfolioStore,{icon,escape:e,toast,design}=UI;
  const root=document.getElementById('admin-app');
  let data, section='items', draft, settings, pendingUploads=0, dirtySettings=false;
  const asset=(value,type)=>Store.assetURL(value,type);
  const names={...(window.AppearanceUI?{appearance:'外观与特效'}:{}),items:'作品管理',settings:'站点设置',password:'管理密码',export:'导入与导出'};
  const fileLabel={thumbnail:'封面图',images:'图片集',videoData:'视频文件',avatar:'个人头像',bgmData:'背景音乐'};
  function field(label,id,value='',options={}){
    return `<div class="field"><label for="${id}">${e(label)}</label>${options.area?`<textarea id="${id}" name="${id}" rows="${options.rows||4}" ${options.required?'required':''}>${e(value)}</textarea>`:`<input id="${id}" name="${id}" type="${options.type||'text'}" value="${e(value)}" ${options.required?'required':''} ${options.placeholder?`placeholder="${e(options.placeholder)}"`:''} ${options.auto?`autocomplete="${options.auto}"`:''}>`}${options.help?`<small>${e(options.help)}</small>`:''}</div>`;
  }
  const select=(label,id,values,value)=>`<div class="field"><label for="${id}">${e(label)}</label><select id="${id}" name="${id}">${values.map(([key,text])=>`<option value="${e(key)}" ${key===value?'selected':''}>${e(text)}</option>`).join('')}</select></div>`;
  function upload(name,group='item'){
    const type=name==='videoData'?'video/mp4,video/webm':name==='bgmData'?'audio/mpeg,audio/wav,audio/ogg':'image/*';
    const multiple=name==='images';
    return `<div class="field"><span class="field-label">${fileLabel[name]}</span><label class="dropzone" data-drop="${name}" data-group="${group}">${icon('upload')}<span>选择文件或拖放到这里</span><small>${name==='videoData'?'MP4 / WebM，最多 100 MB':name==='bgmData'?'MP3 / WAV / OGG，最多 20 MB':'图片文件，单张最多 15 MB'}</small><input type="file" aria-label="上传${fileLabel[name]}" accept="${type}" ${multiple?'multiple':''} data-upload="${name}" data-group="${group}"></label><div class="file-preview" id="preview-${name}"></div></div>`;
  }
  async function loginView(){
    const seed=window.PORTFOLIO_SEED, cover=design==='gallery'?'../shared/assets/portal.png':asset(seed.items[4]?.thumbnail||seed.items[0]?.thumbnail);
    root.innerHTML=`<main class="login-screen"><section class="login-art"><img class="login-image" src="${e(cover)}" alt=""><a class="login-brand" href="index.html">${e(seed.siteInfo.name)}<span class="accent">.</span></a><div><h1>${design==='cinema'?'每一帧，<br>都有你的表达。':'创作的下一帧，<br>由你定义。'}</h1><p>${design==='cinema'?'沉浸影院':'数字创作展厅'} / CONTENT STUDIO</p></div></section><section class="login-form-side"><form class="login-box" id="login-form"><p class="eyebrow">CONTENT STUDIO</p><h2>欢迎回来</h2><p>登录后管理作品、个人信息与媒体。</p>${field('管理密码','login-password','',{type:'password',required:true,auto:'current-password'})}<button class="button primary" type="submit">进入管理 ${icon('arrow')}</button><div class="login-error" id="login-error" role="alert"></div><div class="login-back"><a href="index.html">← 返回作品集</a><span>首次预览：admin123</span></div></form></section></main>`;
    if(window.AppearanceUI)AppearanceUI.decorate(await Store.get(),root);
    root.querySelector('#login-form').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{if(await Store.login(document.getElementById('login-password').value))await init();else document.getElementById('login-error').textContent='密码不正确，请重试。';}catch(error){document.getElementById('login-error').textContent=error.message;}finally{button.disabled=false;}};
  }
  function shell(){
    root.innerHTML=`<aside class="admin-sidebar"><a class="admin-brand" href="index.html">${e(data.siteInfo.name)}<span>.</span></a><p class="eyebrow">CONTENT STUDIO</p><nav class="admin-nav" aria-label="后台导航">${[['items','grid'],...(window.AppearanceUI?[['appearance','sun']]:[]),['settings','settings'],['password','lock'],['export','download']].map(([key,ic])=>`<button data-section="${key}" class="${section===key?'active':''}">${icon(ic)}${names[key]}</button>`).join('')}<a href="resume.html" target="_blank" rel="noopener">${icon('file')}个人简历</a><button id="logout">${icon('logout')}退出登录</button></nav><div class="sidebar-bottom"><p>两种设计共用本机编辑数据</p><a href="../${design==='cinema'?'gallery':'cinema'}/admin.html">切换${design==='cinema'?'展厅':'影院'}版后台 ${icon('arrow')}</a></div></aside><main class="admin-main"><header class="admin-header"><div><p class="eyebrow">${design==='cinema'?'CINEMA / 沉浸影院':'GALLERY / 数字创作展厅'}</p><h1 id="admin-title">${names[section]}</h1></div><div class="top-actions"><button class="icon-button" data-theme-toggle aria-label="切换亮暗主题">${icon('sun')}</button><a class="button" href="index.html" target="_blank" rel="noopener">预览网站 ${icon('arrow')}</a></div></header><div id="admin-content"></div></main>`;
    if(window.AppearanceUI)AppearanceUI.decorate(data,root);
    UI.bindTheme();
    root.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>navigate(button.dataset.section));
    root.querySelector('#logout').onclick=async()=>{if((dirtySettings||window.AppearanceUI?.isDirty())&&!await confirmAction('放弃未保存的设置？','退出后，当前未保存的修改将不会保留。','退出登录'))return;Store.logout();location.reload();};
    renderSection();
  }
  async function navigate(next){if((dirtySettings||window.AppearanceUI?.isDirty())&&!await confirmAction('离开设置？','当前修改还没有保存。','放弃修改'))return;dirtySettings=false;window.AppearanceUI?.dispose();section=next;root.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===section));root.querySelector('#admin-title').textContent=names[section];renderSection();window.scrollTo({top:0,behavior:'smooth'});}
  function renderSection(){
    const content=document.getElementById('admin-content');
    if(section==='items'){
      content.innerHTML=`<div class="admin-toolbar"><p><strong>${data.items.length}</strong> 部作品 · ${data.items.filter(x=>x.featured).length} 部精选</p><button class="button primary" id="new-item">${icon('plus')}添加作品</button></div><div class="items-list">${data.items.map(item=>`<article class="admin-item">${asset(item.thumbnail)?`<img class="admin-item-thumb" src="${e(asset(item.thumbnail))}" alt="${e(item.title)}" loading="lazy">`:'<div class="admin-item-thumb image-empty">—</div>'}<div><h3>${e(item.title)}</h3><div class="item-meta"><span>${e(item.category)}</span><span>·</span><span>${item.type==='image'?'图片集':item.videoData?'本地视频':'平台链接'}</span>${item.featured?'<span class="badge featured">精选</span>':''}</div></div><div class="item-actions"><a class="icon-button" href="index.html?project=${encodeURIComponent(item.id)}" target="_blank" rel="noopener" aria-label="预览${e(item.title)}">${icon('eye')}</a><button class="button" data-edit="${e(item.id)}">${icon('edit')}编辑</button><button class="icon-button danger" data-delete="${e(item.id)}" aria-label="删除${e(item.title)}">${icon('trash')}</button></div></article>`).join('')||'<div class="empty-state">还没有作品，添加第一部作品吧。</div>'}</div>`;
      content.querySelector('#new-item').onclick=()=>openEditor();
      content.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));
      content.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const item=data.items.find(x=>x.id===b.dataset.delete);if(!await confirmAction('删除这部作品？',item.title,'删除作品'))return;try{data=await Store.removeItem(item.id);renderSection();toast('作品已删除');}catch(error){toast(error.message,true);}});
    }else if(section==='appearance'&&window.AppearanceUI)AppearanceUI.render(content,{data,onSaved:next=>{data=next;}});
    else if(section==='settings')renderSettings(content);
    else if(section==='password'){
      content.innerHTML=`<form id="password-form" class="section-panel password-panel"><p class="panel-description">更新这些预览共用的本机管理密码。</p><div class="form-section">${field('当前密码','old-password','',{type:'password',required:true,auto:'current-password'})}${field('新密码','new-password','',{type:'password',required:true,auto:'new-password',help:'至少 6 个字符'})}${field('再次输入新密码','repeat-password','',{type:'password',required:true,auto:'new-password'})}<div class="form-footer"><button class="button primary" type="submit">保存密码 ${icon('check')}</button></div></div></form>`;
      content.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;try{const newPassword=content.querySelector('#new-password').value;if(newPassword!==content.querySelector('#repeat-password').value)throw new Error('两次输入的新密码不一致。');await Store.changePassword(content.querySelector('#old-password').value,newPassword);event.target.reset();toast('管理密码已更新');}catch(error){toast(error.message,true);}finally{button.disabled=false;}};
    }else renderExport(content);
  }
  function openEditor(id){
    draft=JSON.parse(JSON.stringify(data.items.find(x=>x.id===id)||{title:'',category:'',type:'video',description:'',videoUrl:'',embedUrl:'',videoData:null,videoSource:'embed',thumbnail:null,images:[],tags:[],featured:false}));
    const dialog=document.getElementById('editor-dialog');
    dialog.innerHTML=`<header class="editor-head"><div><p class="eyebrow">PROJECT EDITOR</p><h2 id="editor-title">${id?'编辑作品':'添加作品'}</h2></div><button type="button" class="icon-button" data-editor-close aria-label="关闭编辑器">${icon('close')}</button></header><form class="editor-form" id="item-form"><div class="form-grid">${field('作品标题 *','item-title',draft.title,{required:true})}${field('分类 *','item-category',draft.category,{required:true,placeholder:'真人短剧 / 2d漫剧 / 3d漫剧'})}</div><div class="form-grid">${select('作品类型','item-type',[['video','视频作品'],['image','图片集']],draft.type)}${field('原平台链接','item-videoUrl',draft.videoUrl,{help:'可直接粘贴带文字的平台分享链接'})}</div>${field('作品描述','item-description',draft.description,{area:true,rows:5})}<div id="video-fields">${select('视频来源','item-videoSource',[['embed','平台链接 / 嵌入播放'],['upload','上传本地视频']],draft.videoSource||(draft.videoData?'upload':'embed'))}<div id="embed-field">${field('嵌入播放地址','item-embedUrl',draft.embedUrl,{help:'普通分享链接会显示封面和原平台入口；兼容的播放器链接可直接播放。'})}</div><div id="upload-video-field">${upload('videoData')}</div></div><div class="form-grid"><div>${upload('thumbnail')}</div><div id="images-field">${upload('images')}</div></div>${field('标签','item-tags',(draft.tags||[]).join(', '),{help:'使用逗号分隔多个标签'})}<label class="check-field"><input type="checkbox" id="item-featured" ${draft.featured?'checked':''}>设为精选作品</label><div class="form-footer"><span class="save-state" id="item-save-state"></span><button class="button" type="button" data-editor-close>取消</button><button class="button primary" id="save-item" type="submit">保存作品 ${icon('check')}</button></div></form>`;
    dialog.setAttribute('aria-labelledby','editor-title');
    dialog.querySelectorAll('[data-editor-close]').forEach(b=>b.onclick=()=>dialog.close());
    const updateConditional=()=>{const video=document.getElementById('item-type').value==='video';document.getElementById('video-fields').hidden=!video;document.getElementById('images-field').hidden=video;const uploaded=document.getElementById('item-videoSource').value==='upload';document.getElementById('embed-field').hidden=uploaded;document.getElementById('upload-video-field').hidden=!uploaded;};
    dialog.querySelector('#item-type').onchange=updateConditional;dialog.querySelector('#item-videoSource').onchange=updateConditional;updateConditional();
    bindUploads(dialog);['thumbnail','images','videoData'].forEach(name=>previewFile(name,'item'));
    dialog.querySelector('#item-form').onsubmit=async event=>{
      event.preventDefault();if(pendingUploads){toast('文件正在读取，请稍候再保存。',true);return;}
      const value=id=>document.getElementById(id).value.trim();
      if(!value('item-title')||!value('item-category')){toast('请填写作品标题和分类。',true);return;}
      const item={...draft,title:value('item-title'),category:value('item-category'),type:value('item-type'),description:value('item-description'),videoUrl:value('item-videoUrl'),embedUrl:value('item-embedUrl'),videoSource:value('item-videoSource'),tags:value('item-tags').split(/[,，]/).map(x=>x.trim()).filter(Boolean),featured:document.getElementById('item-featured').checked};
      if(item.videoSource==='embed')item.videoData=null;
      const button=document.getElementById('save-item');button.disabled=true;document.getElementById('item-save-state').textContent='正在保存…';
      try{data=await Store.saveItem(item,id);dialog.close();renderSection();toast(id?'作品已更新':'作品已添加');}catch(error){toast(error.message,true);}finally{button.disabled=false;document.getElementById('item-save-state').textContent='';}
    };
    dialog.showModal();
  }
  function renderSettings(content){
    settings=JSON.parse(JSON.stringify(data.siteInfo));dirtySettings=false;
    content.innerHTML=`<form id="settings-form" class="section-panel"><div class="form-section"><h3>首页信息</h3><div class="form-grid">${field('主页标题','site-mainTitle',settings.mainTitle)}${field('标语','site-slogan',settings.slogan||'')}${field('姓名','site-name',settings.name,{required:true})}${field('个人副标题','site-title',settings.title)}</div><div style="margin-top:22px">${field('个人简介','site-bio',settings.bio,{area:true,rows:4})}</div>${field('技能标签','site-skillTags',(settings.skillTags||[]).join(', '),{help:'使用逗号分隔；保留原有名称即可'})}</div><div class="form-section"><h3>媒体与音乐</h3><div class="form-grid"><div>${upload('avatar','settings')}</div><div>${upload('bgmData','settings')}</div></div><div class="field"><label for="site-volume">默认音量 <span id="volume-value">${settings.bgmVolume??30}%</span></label><input id="site-volume" type="range" min="0" max="100" value="${settings.bgmVolume??30}" style="accent-color:var(--accent)"><small>访客可主动开启音乐。</small></div></div><div class="form-section"><h3>联系方式</h3><div id="social-editor"></div><button class="button" id="add-social" type="button">${icon('plus')}添加联系方式</button></div><div class="settings-bottom"><button class="button primary" id="save-settings" type="submit">保存设置 ${icon('check')}</button></div></form>`;
    bindUploads(content);previewFile('avatar','settings');previewFile('bgmData','settings');renderSocial();
    content.querySelector('#add-social').onclick=()=>{settings.socialLinks.push({icon:'',platform:'',url:''});dirtySettings=true;renderSocial();};
    content.querySelector('#site-volume').oninput=event=>{document.getElementById('volume-value').textContent=event.target.value+'%';};
    content.querySelector('form').addEventListener('input',()=>dirtySettings=true);
    content.querySelector('form').onsubmit=async event=>{event.preventDefault();if(pendingUploads){toast('文件正在读取，请稍候再保存。',true);return;}const val=id=>document.getElementById(id).value.trim();const next={...settings,mainTitle:val('site-mainTitle'),slogan:val('site-slogan'),name:val('site-name'),title:val('site-title'),bio:val('site-bio'),skillTags:val('site-skillTags').split(/[,，]/).map(x=>x.trim()).filter(Boolean),bgmVolume:Number(val('site-volume'))};if(!next.name){toast('请填写姓名',true);return;}const button=document.getElementById('save-settings');button.disabled=true;try{data=await Store.saveSite(next);dirtySettings=false;toast('设置已保存，所有设计都会更新');}catch(error){toast(error.message,true);}finally{button.disabled=false;}};
  }
  function renderSocial(){const target=document.getElementById('social-editor');target.innerHTML=settings.socialLinks.map((link,i)=>`<div class="social-row"><input aria-label="第 ${i+1} 项图标" data-social="${i}" data-field="icon" value="${e(link.icon)}" placeholder="图标"><input aria-label="第 ${i+1} 项平台名称" data-social="${i}" data-field="platform" value="${e(link.platform)}" placeholder="平台名称"><input aria-label="第 ${i+1} 项联系方式" data-social="${i}" data-field="url" value="${e(link.url)}" placeholder="邮箱、账号或链接"><button type="button" class="icon-button danger" data-remove-social="${i}" aria-label="移除第 ${i+1} 项联系方式">${icon('close')}</button></div>`).join('');target.querySelectorAll('[data-social]').forEach(input=>input.oninput=()=>{settings.socialLinks[Number(input.dataset.social)][input.dataset.field]=input.value;dirtySettings=true;});target.querySelectorAll('[data-remove-social]').forEach(button=>button.onclick=()=>{settings.socialLinks.splice(Number(button.dataset.removeSocial),1);dirtySettings=true;renderSocial();});}
  function bindUploads(scope){
    scope.querySelectorAll('[data-upload]').forEach(input=>input.onchange=()=>loadFiles(input.files,input.dataset.upload,input.dataset.group));
    scope.querySelectorAll('[data-drop]').forEach(zone=>{zone.ondragover=event=>{event.preventDefault();zone.classList.add('dragover');};zone.ondragleave=()=>zone.classList.remove('dragover');zone.ondrop=event=>{event.preventDefault();zone.classList.remove('dragover');loadFiles(event.dataTransfer.files,zone.dataset.drop,zone.dataset.group);};});
  }
  async function loadFiles(files,name,group){
    const list=Array.from(files);if(!list.length)return;
    const allowed=name==='videoData'?'video/':name==='bgmData'?'audio/':'image/',limit=name==='videoData'?100:name==='bgmData'?20:15;
    const target=group==='settings'?settings:draft;
    pendingUploads++;
    try{const values=[];for(const file of(name==='images'?list:list.slice(0,1))){if(!file.type.startsWith(allowed))throw new Error('文件格式不匹配，请选择'+fileLabel[name]+'。');if(file.size>limit*1024*1024)throw new Error(`文件超过 ${limit} MB，请换用较小的文件。`);values.push(await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('文件读取失败'));reader.readAsDataURL(file);}));}if(name==='images')target.images.push(...values);else target[name]=values[0];if(group==='settings')dirtySettings=true;previewFile(name,group);}
    catch(error){toast(error.message,true);}finally{pendingUploads--;}
  }
  function previewFile(name,group){
    const container=document.getElementById('preview-'+name);if(!container)return;const obj=group==='settings'?settings:draft;const values=name==='images'?obj.images:(obj[name]?[obj[name]]:[]);
    container.innerHTML=values.map((value,i)=>`<div class="preview-thumb">${name==='bgmData'?`<audio src="${e(asset(value,'audio'))}" controls preload="none"></audio>`:name==='videoData'?`<video src="${e(asset(value,'video'))}" controls preload="metadata"></video>`:`<img src="${e(asset(value))}" alt="${fileLabel[name]}预览">`}<button type="button" data-clear="${i}" aria-label="移除${fileLabel[name]}">×</button></div>`).join('');container.querySelectorAll('[data-clear]').forEach(button=>button.onclick=()=>{if(name==='images')obj.images.splice(Number(button.dataset.clear),1);else obj[name]=null;if(group==='settings')dirtySettings=true;previewFile(name,group);});
  }
  function renderExport(content){
    content.innerHTML=`<div class="section-panel"><p class="panel-description">导出可备份的完整数据，或带有当前作品的独立首页。</p><div class="export-options"><article class="export-option">${icon('download')}<h3>完整数据备份</h3><p>保存作品、图片、音乐和站点设置。可重新导入新版，也兼容原有数据结构。</p><button class="button primary" id="export-json">导出 JSON ${icon('download')}</button></article><article class="export-option">${icon('file')}<h3>独立首页</h3><p>将当前设计、作品图片和音乐打包进一个 HTML。简历与后台保留在完整预览文件夹中。</p><button class="button" id="export-html">导出 HTML ${icon('download')}</button></article></div><div class="maintenance"><div><h3>导入作品集数据</h3><p>支持原有 settings.json 和新版 JSON 备份。导入前会显示确认。</p></div><label class="button file-input-button">选择 JSON ${icon('upload')}<input id="import-json" type="file" accept=".json,application/json" aria-label="导入作品集 JSON"></label></div><div class="maintenance"><div><h3>恢复原始导入数据</h3><p>恢复为本次从原网站提取的六部作品和站点设置。</p></div><button class="button danger" id="reset-data">恢复原始数据</button></div><p id="export-status" role="status" class="panel-description" style="margin-top:25px"></p></div>`;
    content.querySelector('#export-json').onclick=()=>runExport('json');content.querySelector('#export-html').onclick=()=>runExport('html');
    content.querySelector('#import-json').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>180*1024*1024)throw new Error('JSON 文件超过 180 MB。');const incoming=Store.validateImport(JSON.parse(await file.text()));if(!await confirmAction('替换当前作品数据？',`将导入 ${incoming.items.length} 部作品和对应站点设置。各套设计会同时更新，请先导出需要保留的数据。`,'导入数据'))return;data=await Store.replace(incoming);toast('数据已导入');}catch(error){toast(error.message,true);}finally{event.target.value='';}};
    content.querySelector('#reset-data').onclick=async()=>{if(!await confirmAction('恢复原始数据？','当前修改将被本次原始导入数据替换。管理密码保持不变。','恢复原始数据'))return;try{data=await Store.reset();toast('已恢复原始数据');}catch(error){toast(error.message,true);}};
  }
  async function runExport(type){const buttons=[...document.querySelectorAll('#export-json,#export-html')];buttons.forEach(b=>b.disabled=true);const status=document.getElementById('export-status');status.textContent='正在打包媒体，请稍候…';try{await PortfolioExport[type](await Store.get(true),design);status.textContent='导出完成，文件已开始下载。';}catch(error){status.textContent=error.message;toast(error.message,true);}finally{buttons.forEach(b=>b.disabled=false);}}
  function confirmAction(title,description,action){const dialog=document.getElementById('confirm-dialog');return new Promise(resolve=>{dialog.innerHTML=`<h2 id="confirm-title">${e(title)}</h2><p>${e(description)}</p><div class="button-row"><button class="button" value="cancel">取消</button><button class="button primary" value="confirm">${e(action)}</button></div>`;dialog.setAttribute('aria-labelledby','confirm-title');dialog.returnValue='cancel';dialog.querySelectorAll('button').forEach(b=>b.onclick=()=>dialog.close(b.value));dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});dialog.showModal();});}
  async function init(){try{data=await Store.get();shell();const request=new URLSearchParams(location.search).get('section');if(names[request])navigate(request);}catch(error){root.innerHTML=`<main class="page-error"><h1>后台暂时无法读取数据</h1><p>${e(error.message)}</p><button class="button" onclick="location.reload()">重新加载</button></main>`;}}
  window.addEventListener('portfolio:external-update',async()=>{if(!Store.isAuthenticated())return;data=await Store.get(true);if(section==='items')renderSection();else toast('另一窗口更新了数据；当前未保存的表单仍保留。');});
  window.addEventListener('beforeunload',event=>{if(dirtySettings||window.AppearanceUI?.isDirty()){event.preventDefault();event.returnValue='';}});
  if(Store.isAuthenticated())init();else loginView();
})();
