(() => {
  'use strict';
  const T=PortfolioThemes,S=PortfolioStore,{escape:e,icon,toast}=UI;
  let draft,dirty=false,pending=0,generation=0;
  const field=(label,id,value,type='text',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${e(value)}" ${extra}></div>`;
  function decorate(data,root){
    const config=T.resolve(data);T.apply(config);
    const brand=root.querySelector('.admin-brand');if(brand)brand.innerHTML=e(data.siteInfo.name)+'<span> / STUDIO</span>';
    const overline=root.querySelector('.admin-header .eyebrow');if(overline)overline.textContent='CREATIVE CONTROL / '+config.name;
    const footer=root.querySelector('.sidebar-bottom');if(footer)footer.innerHTML=`<p>三种设计，共用作品与个人信息。</p><a href="index.html" target="_blank" rel="noopener">打开当前作品集 ${icon('arrow')}</a>`;
    root.querySelectorAll('a[href="resume.html"]').forEach(a=>a.href=T.link('resume.html',config.theme));
    root.querySelectorAll('.login-art p').forEach(p=>p.textContent='CREATIVE CONTROL / 创作管理');
    const loginImage=root.querySelector('.login-image');if(loginImage)loginImage.src=config.theme==='portal'?'../shared/assets/world-gate.png':S.assetURL(data.items.find(x=>x.id===config.heroId)?.thumbnail||data.items[0]?.thumbnail);
  }
  function render(container,{data,onSaved}){
    draft=T.normalize(data.siteInfo.presentation);dirty=false;const session=++generation;
    const themeCards=()=>Object.entries(T.defaults).map(([key,value],i)=>{const item=data.items.find(x=>x.id===draft.themes[key].heroId)||data.items[i]||data.items[0];return `<button type="button" class="appearance-choice ${key}" data-design-choice="${key}" aria-pressed="${draft.theme===key}"><span class="choice-preview"><img src="${e(S.assetURL(item?.thumbnail))}" alt="" loading="lazy"><b>${key==='frames'?'帧之间':key==='portal'?e(data.siteInfo.name):'故事，<br>不止一格。'}</b><i aria-hidden="true">0${i+1}</i></span><span class="choice-name"><strong>${value.name}</strong><span class="choice-check">${icon('check')}</span></span><small>${['悬浮画面 · 镜头推进','整屏镜头 · 裂缝穿越','漫画分格 · 黑白转彩'][i]}</small></button>`;}).join('');
    container.innerHTML=`<form id="appearance-form" class="appearance-form"><p class="panel-description">选择网站默认设计；每套设计的主视觉与配色可分别保存。</p><div class="appearance-choices" role="group" aria-label="网站默认设计">${themeCards()}</div><div class="appearance-editor"><section class="form-section"><div class="appearance-section-title"><h3 id="editing-theme-name"></h3><span>THEME DETAILS</span></div><div id="theme-fields"></div></section><section class="form-section effects-settings"><div class="appearance-section-title"><h3>镜头与质感</h3><span>ALL THEMES</span></div><div class="field"><label for="effect-motion">动效强度 <output id="motion-label">${draft.motion===0?'关闭':Math.round(draft.motion*100)+'%'}</output></label><input type="range" id="effect-motion" min="0" max="1.5" step="0.1" value="${draft.motion}"><small>0 为静态；100% 为推荐强度。设备开启“减少动态效果”时自动停用。</small></div><label class="effect-switch"><span>鼠标视差<small>画面随鼠标产生轻微空间变化</small></span><input type="checkbox" id="effect-parallax" ${draft.parallax?'checked':''}></label><label class="effect-switch"><span>胶片颗粒<small>叠加细微的画面质感</small></span><input type="checkbox" id="effect-grain" ${draft.grain?'checked':''}></label><div class="customize-note">作品封面、标题、视频与分类在「作品管理」中更换；头像、简介与音乐在「站点设置」中更换。</div></section></div><div class="settings-bottom appearance-save"><span id="appearance-state" role="status">尚未修改</span><a class="button" id="appearance-preview" href="index.html?theme=${draft.theme}" target="_blank" rel="noopener">查看已保存效果 ${icon('eye')}</a><button class="button primary" type="submit" id="save-appearance">保存并应用 ${icon('check')}</button></div></form>`;
    const fields=container.querySelector('#theme-fields');
    const mark=()=>{dirty=true;container.querySelector('#appearance-state').textContent=pending?'正在读取媒体…':'有未保存的修改';};
    function readFields(){const current=draft.themes[draft.theme];for(const key of ['heroTitle','heading','heroId','appearance','accent','focus','font','typeScale','titlePosition']){const input=fields.querySelector('[data-config="'+key+'"]');if(input)current[key]=['focus','typeScale'].includes(key)?Number(input.value):input.value;}}
    function previewFiles(){const current=draft.themes[draft.theme];for(const type of ['image','video']){const target=fields.querySelector('#custom-'+type+'-preview'),src=S.assetURL(current[type],type==='video'?'video':'image');target.innerHTML=src?`${type==='image'?`<img src="${e(src)}" alt="自定义主视觉">`:`<video src="${e(src)}" controls preload="metadata"></video>`}<button type="button" class="button" data-remove-visual="${type}">恢复默认</button>`:'<small>使用默认'+(type==='image'?'画面':'静态画面')+'</small>';target.querySelector('button')?.addEventListener('click',()=>{current[type]='';mark();previewFiles();});}}
    function renderOrder(){
      const current=draft.themes[draft.theme],known=data.items.map(x=>x.id);current.projectOrder=[...current.projectOrder.filter(id=>known.includes(id)),...known.filter(id=>!current.projectOrder.includes(id))];
      const target=fields.querySelector('#home-order-list');
      target.innerHTML=current.projectOrder.map((id,i)=>{const item=data.items.find(x=>x.id===id);return `<div class="home-order-row"><span>${String(i+1).padStart(2,'0')}</span><img src="${e(S.assetURL(item.thumbnail))}" alt=""><strong>${e(item.title)}</strong><button type="button" class="icon-button" data-move="${i}" data-step="-1" aria-label="前移${e(item.title)}" ${i===0?'disabled':''}>↑</button><button type="button" class="icon-button" data-move="${i}" data-step="1" aria-label="后移${e(item.title)}" ${i===current.projectOrder.length-1?'disabled':''}>↓</button></div>`;}).join('');
      target.querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>{const i=Number(button.dataset.move),j=i+Number(button.dataset.step);[current.projectOrder[i],current.projectOrder[j]]=[current.projectOrder[j],current.projectOrder[i]];mark();renderOrder();});
    }
    function renderFields(){
      const current=draft.themes[draft.theme];
      container.querySelector('#editing-theme-name').textContent=T.defaults[draft.theme].name+' · 主视觉';
      container.querySelectorAll('[data-design-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.designChoice===draft.theme)));
      container.querySelector('#appearance-preview').href=T.link('index.html',draft.theme);
      fields.innerHTML=`<div class="form-grid typography-fields">${field('首页主标题','visual-title',current.heroTitle||data.siteInfo.name,'text','maxlength="24" data-config="heroTitle"')}<div class="field"><label for="visual-font">标题字体</label><select id="visual-font" data-config="font">${[['modern','现代黑体'],['editorial','粗体海报'],['serif','宋体 / 衬线']].map(([key,label])=>`<option value="${key}" ${current.font===key?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="field typography-size"><label for="visual-typeScale">标题大小 <output id="typeScale-label">${Math.round(current.typeScale*100)}%</output></label><input id="visual-typeScale" type="range" min="0.65" max="1.3" step="0.05" value="${current.typeScale}" data-config="typeScale"></div><div class="form-grid">${field('一句开场白','visual-heading',current.heading,'text','maxlength="42" data-config="heading"')}<div class="field"><label for="visual-project">首页主作品</label><select id="visual-project" data-config="heroId">${!data.items.some(x=>x.id===current.heroId)?'<option value="">自动使用首部精选作品</option>':''}${data.items.map(x=>`<option value="${e(x.id)}" ${x.id===current.heroId?'selected':''}>${e(x.title)}</option>`).join('')}</select></div></div><div class="form-grid appearance-colors"><div class="field"><label for="visual-accent">强调色</label><div class="color-pair"><input type="color" id="visual-accent" data-config="accent" value="${e(current.accent)}"><input id="visual-hex" aria-label="强调色色号" value="${e(current.accent)}" pattern="#[0-9a-fA-F]{6}" maxlength="7"></div></div><div class="field"><label for="visual-appearance">页面底色</label><select id="visual-appearance" data-config="appearance"><option value="dark" ${current.appearance==='dark'?'selected':''}>深色</option><option value="light" ${current.appearance==='light'?'selected':''}>浅色</option></select></div></div><div class="field focus-field"><label for="visual-focus">开场封面取景位置 <output id="focus-label">${current.focus}%</output></label><input id="visual-focus" type="range" min="0" max="100" value="${current.focus}" data-config="focus"><small>0% 靠上，100% 靠下。</small></div><div class="form-grid appearance-uploads">${['image','video'].map(type=>`<div class="field"><label for="custom-${type}">${type==='image'?('更换开场图片'):'开场动态视频'}</label><label class="dropzone">${icon('upload')}<span>${type==='image'?'上传图片':'上传 MP4 / WebM'}</span><small>${type==='image'?'高清作品画面 · 最多 15 MB':'静音循环播放 · 最多 60 MB'}</small><input type="file" id="custom-${type}" data-custom-file="${type}" accept="${type==='image'?'image/*':'video/mp4,video/webm'}"></label><div class="custom-media-preview" id="custom-${type}-preview"></div></div>`).join('')}</div>${draft.theme==='portal'?'<p class="form-help">开场图片会铺满整个场景。作品本身的封面与视频在「作品管理」中更换。</p>':''}`;
      fields.insertAdjacentHTML('beforeend','<div class="home-order"><h4>首页作品顺序</h4><p>主作品以外的开场画面，以及下方作品展示，都会按此顺序排列。</p><div id="home-order-list"></div></div>');
      renderOrder();
      if(draft.theme==='portal'){
        fields.insertAdjacentHTML('beforeend',`<div class="field title-position-field"><label for="visual-title-position">姓名排版位置</label><select id="visual-title-position" data-config="titlePosition">${[['left','左侧'],['center','居中'],['right','右侧']].map(([key,label])=>`<option value="${key}" ${key===current.titlePosition?'selected':''}>${label}</option>`).join('')}</select></div><div id="rift-scene-editor"></div>`);
        if(window.RiftSceneEditor)RiftSceneEditor.render(fields.querySelector('#rift-scene-editor'),{items:data.items,theme:current,onChange:mark});
      }
      previewFiles();
      fields.querySelectorAll('[data-config]').forEach(input=>input.addEventListener('input',()=>{readFields();if(input.dataset.config==='accent')fields.querySelector('#visual-hex').value=input.value;if(input.dataset.config==='focus')fields.querySelector('#focus-label').textContent=input.value+'%';if(input.dataset.config==='typeScale')fields.querySelector('#typeScale-label').textContent=Math.round(Number(input.value)*100)+'%';mark();}));
      fields.querySelector('#visual-hex').addEventListener('input',event=>{if(/^#[0-9a-f]{6}$/i.test(event.target.value)){fields.querySelector('#visual-accent').value=event.target.value;readFields();}mark();});
      fields.querySelectorAll('[data-custom-file]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;const type=input.dataset.customFile,theme=draft.theme;pending++;mark();container.querySelector('#save-appearance').disabled=true;try{if(type==='video'?!['video/mp4','video/webm'].includes(file.type):!file.type.startsWith('image/'))throw new Error('请选择兼容的媒体文件。');if(file.size>(type==='image'?15:60)*1024*1024)throw new Error('文件太大，请使用较小的媒体。');const value=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('读取失败，请重新选择文件。'));reader.readAsDataURL(file);});if(generation!==session)return;draft.themes[theme][type]=value;if(theme===draft.theme)previewFiles();}catch(error){toast(error.message,true);}finally{pending--;if(generation===session){mark();container.querySelector('#save-appearance').disabled=pending>0;}}}));
    }
    container.querySelectorAll('[data-design-choice]').forEach(button=>button.addEventListener('click',()=>{readFields();draft.theme=button.dataset.designChoice;renderFields();mark();}));
    container.querySelector('#effect-motion').addEventListener('input',event=>{draft.motion=Number(event.target.value);container.querySelector('#motion-label').textContent=draft.motion===0?'关闭':Math.round(draft.motion*100)+'%';mark();});
    for(const key of ['grain','parallax'])container.querySelector('#effect-'+key).addEventListener('change',event=>{draft[key]=event.target.checked;mark();});
    container.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();if(pending){toast('媒体仍在读取，请稍候。',true);return;}readFields();const button=container.querySelector('#save-appearance');button.disabled=true;try{const saved=await S.saveSite({presentation:T.normalize(draft)});dirty=false;onSaved(saved);decorate(saved,document.getElementById('admin-app'));container.querySelector('#appearance-state').textContent='已保存 · 当前默认：'+T.defaults[draft.theme].name;toast('外观已应用，作品集与简历已同步');}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
    renderFields();
  }
  window.AppearanceUI={render,decorate,isDirty:()=>dirty||pending>0,dispose:()=>{generation++;dirty=false;}};
})();
