(() => {
  'use strict';
  const {escape:e,icon}=UI, T=PortfolioThemes, Store=PortfolioStore;
  let activeWorld, config, data, controller, observer, frame=0, particlesFrame=0, root, motionQuery;
  const asset=(src,type)=>Store.assetURL(src,type);
  const img=(src,alt='',attrs='')=>asset(src)?`<img src="${e(asset(src))}" alt="${e(alt)}" ${attrs}>`:'<span class="image-empty">暂无封面</span>';
  const num=n=>String(n).padStart(2,'0');
  const chosen=()=>data.items.find(x=>x.id===config.heroId)||data.items.find(x=>x.featured)||data.items[0];
  const media=(item,attrs='')=>config.video?`<video src="${e(asset(config.video,'video'))}" poster="${e(asset(config.image||item?.thumbnail))}" muted loop playsinline preload="metadata" data-ambient ${attrs}></video>`:img(config.image||item?.thumbnail,item?.title||'',attrs);
  const picker=()=>`<label class="theme-picker"><span class="sr-only">切换作品集设计</span><select id="design-picker" aria-label="切换作品集设计">${Object.entries(T.defaults).map(([key,value])=>`<option value="${key}" ${key===config.theme?'selected':''}>${value.name}</option>`).join('')}</select></label>`;
  function configure(next){config=T.resolve(next);const order=config.projectOrder||[];const rank=id=>order.includes(id)?order.indexOf(id):order.length;data={...next,items:[...next.items].sort((a,b)=>rank(a.id)-rank(b.id))};activeWorld=chosen();T.apply(config);if(config.theme==='portal'&&window.Rift)Rift.configure(data,config);}
  function navbar(info){if(config.theme==='portal'&&window.Rift)return Rift.navbar(info,picker());return `<a href="#main" class="skip-link">跳到正文</a><header class="topbar immersive-nav"><a class="brand" href="#home"><span class="brand-mark" aria-hidden="true">[ JH ]</span>${e(info.name)}<small>VISUAL ARTIST</small></a><nav class="navlinks" aria-label="主导航" id="navlinks"><a href="#works" data-section="works">作品</a><a href="#experience" data-section="experience">经历</a><a href="#about" data-section="about">关于</a><a class="nav-resume" href="${T.link('resume.html',config.theme)}">个人简历 ${icon('arrow')}</a></nav><div class="top-actions">${picker()}<button class="icon-button menu-button" aria-label="展开导航" aria-expanded="false" aria-controls="navlinks" id="menu-toggle">${icon('menu')}</button></div></header>`;}
  function portalHero(info,item){
    return `<section class="camera-section portal-scene portal-observatory" id="home"><div class="camera-sticky"><div class="world-stage">${img(config.image||'../shared/assets/world-gate.png','','class="world-background" fetchpriority="high"')}<button class="world-opening" id="active-gate" ${item?`data-detail="${e(item.id)}"`:''} aria-label="${e(item?'进入作品：'+item.title:'作品入口')}"><span class="portal-window" id="portal-window">${config.video?`<video src="${e(asset(config.video,'video'))}" muted loop playsinline preload="metadata" data-ambient></video>`:img(item?.thumbnail,'','fetchpriority="high"')}</span><span class="gate-mist"></span><span class="gate-threshold" aria-hidden="true"><b>ENTER</b>${icon('arrow')}</span></button></div><canvas class="world-particles" aria-hidden="true"></canvas><div class="world-shade"></div><div class="portal-heading-line"><span>AI FILM / 3D / VR</span><span>${e(info.mainTitle||'个人作品集')} · ${num(data.items.length)} 个故事</span></div><div class="portal-identity"><p class="eyebrow">THE CREATOR</p><h1>${e(config.heroTitle||info.name)}</h1><p class="portal-identity-note">${e(config.heading)}</p><a class="portal-about-link" href="#about">关于我 ${icon('arrow')}</a></div><nav class="world-selector" aria-label="选择开场作品"><p>选择一个故事<span>SELECT A WORLD</span></p>${data.items.map((x,i)=>`<button type="button" data-world="${e(x.id)}" aria-pressed="${x.id===item?.id}"><span class="world-select-index">${num(i+1)}</span><span class="world-select-name">${e(x.title)}</span><span class="world-select-arrow" aria-hidden="true">↗</span></button>`).join('')}</nav><div class="active-world-meta" aria-live="polite"><span id="active-world-category">${e(item?.category||'')}</span><h2 id="active-world-title">${e(item?.title||info.name)}</h2><button class="world-enter-button" id="active-world-enter" ${item?`data-detail="${e(item.id)}"`:''}>进入作品 ${icon('arrow')}</button></div><a class="portal-scroll-next" href="#works">继续探索 ${icon('down')}</a><span class="portal-world-count" aria-hidden="true">0<span id="world-count-number">${item?data.items.indexOf(item)+1:0}</span><i>/ ${num(data.items.length)}</i></span></div></section>`;
  }
  function worldChapters(items,all){return items.map((item,i)=>`<article class="world-chapter" style="--chapter-index:${i}"><span class="chapter-number" aria-hidden="true">${num(all.indexOf(item)+1)}</span><div class="chapter-atmosphere" aria-hidden="true">${img(item.thumbnail,'','loading="lazy"')}</div><div class="chapter-content"><span class="chapter-category">${e(item.category)}</span><h3>${e(item.title)}</h3><button class="chapter-enter" data-detail="${e(item.id)}">进入作品 ${icon('arrow')}</button></div><button class="chapter-door" data-detail="${e(item.id)}" aria-label="进入作品：${e(item.title)}">${img(item.thumbnail,item.title,'loading="lazy" decoding="async"')}<span class="chapter-door-line" aria-hidden="true"></span><span class="chapter-door-hint">${icon('play')}</span></button></article>`).join('')||'<p class="empty-state">这个分类还没有作品。</p>';}
  function bindWorlds(opts){
    root.querySelectorAll('[data-world]').forEach(button=>button.addEventListener('click',()=>{
      const item=data.items.find(x=>x.id===button.dataset.world);if(!item)return;activeWorld=item;
      root.querySelectorAll('[data-world]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));
      const view=root.querySelector('#portal-window');view.querySelectorAll('video').forEach(v=>v.pause());view.innerHTML=img(item.thumbnail,item.title);
      if(config.motion>0&&!motionQuery.matches)view.animate([{clipPath:'inset(0 50% 0 50%)',filter:'brightness(2.2)'},{clipPath:'inset(0 0 0 0)',filter:'brightness(1)'}],{duration:650,easing:'cubic-bezier(.16,1,.3,1)'});
      root.querySelector('#active-world-title').textContent=item.title;root.querySelector('#active-world-category').textContent=item.category;
      const gate=root.querySelector('#active-gate');gate.dataset.detail=item.id;gate.setAttribute('aria-label','进入作品：'+item.title);
      root.querySelector('#active-world-enter').dataset.detail=item.id;root.querySelector('#world-count-number').textContent=data.items.indexOf(item)+1;
    },opts));
  }
  function hero(){
    const item=config.theme==='portal'?activeWorld:chosen(),info=data.siteInfo;
    const signature=`<div class="hero-signature"><span>${e(info.name)} / ${e(info.mainTitle||'个人作品集')}</span><span>AI · FILM · 3D · VR</span></div>`;
    const scroll=`<a class="scroll-cue" href="#works"><span>向下探索</span><span class="scroll-line"></span>${icon('down')}</a>`;
    if(config.theme==='portal')return window.Rift?Rift.hero():portalHero(info,item);
    if(config.theme==='comic')return `<section class="comic-intro" id="home"><div class="comic-masthead"><span>JIAHUI / SELECTED STORIES</span><span>${e(info.mainTitle||'个人作品集')} · ${num(data.items.length)} 部</span></div><div class="comic-opening"><div class="comic-title-panel"><p class="eyebrow">${e(info.name)}的创作现场</p><h1>${e(config.heroTitle||info.name)}<br><span>创作集。</span></h1><p>${e(config.heading==='故事，不止一格。'?'AI 漫剧 · 3D 视觉 · VR 交互':config.heading)}</p><a class="comic-read" href="#works">翻开作品 ${icon('down')}</a><span class="comic-stamp" aria-hidden="true">JH<br>STUDIO</span></div>${item?`<button class="comic-hero-panel" data-detail="${e(item.id)}">${media(item,'fetchpriority="high"')}<span class="comic-bubble">${e(item.category)}</span><span class="comic-hero-caption">${e(item.title)} ${icon('arrow')}</span></button>`:''}<div class="comic-side-panels">${data.items.filter(x=>x!==item).slice(0,2).map((x,i)=>`<button data-detail="${e(x.id)}">${img(x.thumbnail,x.title,'loading="eager"')}<span>${num(i+2)} / ${e(x.title)}</span></button>`).join('')}</div></div><div class="comic-strip" aria-hidden="true"><span>想象</span><b>→</b><span>分镜</span><b>→</b><span>画面</span><b>→</b><span>故事继续</span><b>↘</b></div></section>`;
    const others=data.items.filter(x=>x!==item).slice(0,4);
    return `<section class="camera-section frames-scene" id="home"><div class="camera-sticky">${signature}<div class="frame-grid-lines" aria-hidden="true"></div><div class="frame-copy"><p class="eyebrow">${e(info.mainTitle||'个人作品集')} / AI · FILM · 3D · VR</p><h1>${Array.from(config.heroTitle||info.name).map((char,i)=>`<span class="${i===1?'outlined-type':''}">${e(char)}</span>`).join('')}<i aria-hidden="true">✳</i></h1><p class="hero-subline">${e(config.heading)}</p><a class="frame-explore" href="#works">探索作品 ${icon('arrow')}</a></div><div class="frame-space"><div class="frame-camera">${others.map((x,i)=>`<button class="floating-frame satellite satellite-${i}" data-detail="${e(x.id)}">${img(x.thumbnail,x.title,'fetchpriority="low"')}<span class="frame-label">FRAME ${num(data.items.indexOf(x)+1)}</span></button>`).join('')}${item?`<button class="floating-frame main-frame" data-detail="${e(item.id)}">${media(item,'fetchpriority="high"')}<span class="frame-label"><span>SELECTED / ${e(item.category)}</span>${icon('arrow')}</span><span class="main-frame-title">${e(item.title)}</span></button>`:''}</div></div><div class="frame-bottom"><span class="mono">${num(data.items.length)} 个故事 / 无限种想象</span><span class="film-timeline" aria-hidden="true"><i></i></span><span class="mono">00:<b data-progress>00</b>:24</span></div>${scroll}</div></section>`;
  }
  function cards(next,filter='全部'){
    next=data;
    const items=next.items.filter(x=>filter==='全部'||x.category===filter);
    if(config.theme==='portal')return window.Rift?Rift.indexHTML(items):worldChapters(items,next.items);
    return items.map((item,i)=>`<button class="work-card scene-card" data-detail="${e(item.id)}" style="--card-index:${i}" aria-label="查看${e(item.title)}"><div class="scene-cover">${img(item.thumbnail||(item.images||[])[0],item.title,'loading="lazy" decoding="async"')}<span class="scene-index">${config.theme==='comic'?'#':'FRAME / '}${num(next.items.indexOf(item)+1)}</span><span class="scene-open">${icon(item.type==='video'?'play':'arrow')}<span>展开作品</span></span><span class="scene-reticle" aria-hidden="true"></span></div><div class="scene-caption"><span class="scene-category">${e(item.category)}</span><h3>${e(item.title)}</h3><span class="scene-arrow" aria-hidden="true">↗</span></div></button>`).join('')||'<p class="empty-state">这个分类还没有作品。</p>';
  }
  function works(next,filter){if(config.theme==='portal'&&window.Rift)return '';next=data;const categories=['全部',...new Set(next.items.map(x=>x.category))];return `<section class="immersive-works wrap" id="works"><div class="section-overline"><span>01 / SELECTED WORKS</span><span>${num(next.items.length)} 部作品</span></div><div class="section-heading"><h2>${config.theme==='portal'?'每个世界，都有故事。':config.theme==='comic'?'故事正在发生。':'片段，构成世界。'}</h2><div class="filters" role="group" aria-label="按作品分类筛选">${categories.map(c=>`<button class="filter" data-filter="${e(c)}" aria-pressed="${filter===c}">${e(c)}</button>`).join('')}</div></div><div class="scene-grid" id="work-grid">${cards(next,filter)}</div><p class="sr-only" id="filter-status" role="status"></p></section>`;}
  function bottom(next){if(config.theme==='portal'&&window.Rift)return Rift.bottom();const info=next.siteInfo;return `<section class="journey-section wrap" id="experience"><div class="section-overline"><span>02 / EXPERIENCE</span><span>创作轨迹</span></div><div class="journey-heading"><h2>镜头之外，<br><span>一直向前。</span></h2><a class="text-link" href="${T.link('resume.html',config.theme)}">完整简历 ${icon('arrow')}</a></div><div class="journey-list"><article class="journey-row"><span class="journey-year">2024—</span><h3>AI 漫剧创作<small>独立创作 · 持续探索</small></h3><span class="journey-note">STORY IN PROGRESS</span></article><article class="journey-row"><span class="journey-year">2025</span><h3>星辰征途·红色航天梦<small>测试负责人 · 推动修复 20+ 功能缺陷</small></h3><span class="journey-note">挑战杯红色专项铜奖</span></article><article class="journey-row"><span class="journey-year">2024</span><h3>“数遇·漫步” VR 文旅项目<small>核心开发 · 场景建模 / VR 交互</small></h3><span class="journey-note">浙江省挑战杯铜奖</span></article></div></section><section class="creator-section wrap" id="about"><div class="section-overline"><span>03 / BEHIND THE FRAME</span><span>关于我</span></div><div class="creator-grid"><div class="creator-identity">${img(info.avatar||info.avatarFile,info.name,'loading="lazy"')}<h2>${e(info.name)}<small>${e(info.title)} / 浙江嘉兴</small></h2></div><div class="creator-bio"><p>${e(info.bio)}</p>${info.slogan?`<p>${e(info.slogan)}</p>`:''}<div class="about-tools">${(info.skillTags||[]).map(t=>`<span class="tool-tag">${e(t)}</span>`).join('')}</div></div><div class="contact-list">${UI.socialHTML(info.socialLinks)}</div></div></section><footer class="site-footer wrap"><span>© 2026 ${e(info.name)} · ${e(info.mainTitle||'个人作品集')}</span><a class="back-top" href="#home">回到开场 ↑</a><div class="footer-links"><a href="${T.link('resume.html',config.theme)}">个人简历</a><a href="admin.html?section=appearance">自定义外观</a><a href="admin.html">后台管理</a></div></footer>`;}
  function refreshCards(){
    root?.querySelectorAll('.scene-card,.world-chapter').forEach(el=>observer?.observe(el));
  }
  function bind(nextRoot){
    controller?.abort();observer?.disconnect();cancelAnimationFrame(frame);cancelAnimationFrame(particlesFrame);
    root=nextRoot;controller=new AbortController();const opts={signal:controller.signal};
    motionQuery=matchMedia('(prefers-reduced-motion: reduce)');
    document.title=data.siteInfo.name+' · '+(data.siteInfo.mainTitle||'个人作品集');
    document.getElementById('design-picker')?.addEventListener('change',event=>{const url=new URL(location.href);url.searchParams.set('theme',event.target.value);url.hash='';location.assign(url.href);},opts);
    if(config.theme==='portal'&&window.Rift){Rift.bind(root,controller.signal);return;}
    let px=0,py=0,scrollPending=false;
    bindWorlds(opts);
    const scene=root.querySelector('.camera-section'),sticky=root.querySelector('.camera-sticky');
    const activeMotion=()=>config.motion>0&&!motionQuery.matches;
    const draw=()=>{
      scrollPending=false;if(!scene)return;
      const rect=scene.getBoundingClientRect(),distance=Math.max(1,scene.offsetHeight-innerHeight);
      const p=Math.max(0,Math.min(1,-rect.top/distance));
      sticky.style.setProperty('--travel',activeMotion()?p*config.motion:0);
      sticky.style.setProperty('--pointer-x',activeMotion()&&config.parallax?px:0);
      sticky.style.setProperty('--pointer-y',activeMotion()&&config.parallax?py:0);
      const progress=root.querySelector('[data-progress]');if(progress)progress.textContent=num(Math.round(p*99));
      root.querySelector('.immersive-nav')?.classList.toggle('is-scrolled',scrollY>40);
    };
    const update=()=>{if(!scrollPending){scrollPending=true;frame=requestAnimationFrame(draw);}};
    addEventListener('scroll',update,{...opts,passive:true});addEventListener('resize',update,opts);
    scene?.addEventListener('pointermove',event=>{px=(event.clientX/innerWidth-.5);py=(event.clientY/innerHeight-.5);update();},opts);
    scene?.addEventListener('pointerleave',()=>{px=py=0;update();},opts);
    root.addEventListener('pointermove',event=>{if(!activeMotion()||!config.parallax||event.pointerType==='touch')return;const card=event.target.closest('.scene-card');if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--tilt-x',((event.clientY-r.top)/r.height-.5)*-5*config.motion+'deg');card.style.setProperty('--tilt-y',((event.clientX-r.left)/r.width-.5)*6*config.motion+'deg');card.style.setProperty('--light-x',(event.clientX-r.left)/r.width*100+'%');},opts);
    root.addEventListener('pointerout',event=>{const card=event.target.closest('.scene-card');if(card&&!card.contains(event.relatedTarget)){card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg');}},opts);
    if('IntersectionObserver' in window){observer=new IntersectionObserver(entries=>entries.forEach(entry=>{entry.target.classList.toggle('in-view',entry.isIntersecting);}),{threshold:.08});refreshCards();}
    const videos=[...root.querySelectorAll('[data-ambient]')];
    let sceneVisible=true;
    const manageVideos=()=>root.querySelectorAll('[data-ambient]').forEach(v=>{if(document.hidden||!activeMotion()||!sceneVisible)v.pause();else v.play().catch(()=>{});});
    let videoObserver;if('IntersectionObserver' in window&&scene){videoObserver=new IntersectionObserver(entries=>{sceneVisible=entries[0].isIntersecting;manageVideos();if(sceneVisible)startParticles();});videoObserver.observe(scene);controller.signal.addEventListener('abort',()=>videoObserver.disconnect(),{once:true});}
    addEventListener('visibilitychange',()=>{manageVideos();if(!document.hidden)startParticles();},opts);
    motionQuery.addEventListener('change',()=>{update();manageVideos();startParticles();},opts);
    let canvas=root.querySelector('.world-particles'),context=canvas?.getContext('2d'),last=0,points=Array.from({length:42},()=>({x:Math.random(),y:Math.random(),z:.3+Math.random()*.7}));
    function particles(time){particlesFrame=0;if(!context||document.hidden||!activeMotion()||!sceneVisible)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,1.5);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}context.setTransform(dpr,0,0,dpr,0,0);context.clearRect(0,0,w,h);const delta=Math.min(32,time-last||16);last=time;context.fillStyle=config.accent;for(const p of points){p.y-=delta*.000014*p.z*config.motion;if(p.y<0)p.y=1;context.globalAlpha=p.z*.65;context.beginPath();context.arc(p.x*w,p.y*h,p.z*1.7,0,Math.PI*2);context.fill();}particlesFrame=requestAnimationFrame(particles);}
    function startParticles(){if(!particlesFrame&&context&&activeMotion()&&!document.hidden&&sceneVisible)particlesFrame=requestAnimationFrame(particles);}
    controller.signal.addEventListener('abort',()=>{videos.forEach(v=>v.pause());cancelAnimationFrame(frame);cancelAnimationFrame(particlesFrame);},{once:true});
    manageVideos();draw();startParticles();
  }
  function enter(dialog,origin){
    if(config?.theme==='portal'&&window.Rift){Rift.enter(dialog,origin);return;}
    if(!config?.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
    if(config.theme==='portal'){dialog.animate([{clipPath:'inset(0 49.8% 0 49.8%)',filter:'brightness(3)',opacity:.5},{clipPath:'inset(0 0 0 0)',filter:'brightness(1)',opacity:1}],{duration:850,easing:'cubic-bezier(.16,1,.3,1)'});return;}
    const from=origin?.getBoundingClientRect(),to=dialog.getBoundingClientRect();
    if(from&&to.width&&to.height){const x=from.left+from.width/2-to.left-to.width/2,y=from.top+from.height/2-to.top-to.height/2;dialog.animate([{transform:`translate(${x}px,${y}px) scale(${Math.max(.12,from.width/to.width)},${Math.max(.12,from.height/to.height)})`,opacity:.2,filter:'blur(5px)'},{transform:'translate(0,0) scale(1)',opacity:1,filter:'blur(0px)'}],{duration:520,easing:'cubic-bezier(.16,1,.3,1)'});}else dialog.animate([{opacity:0,transform:'translateY(35px) scale(.94)'},{opacity:1,transform:'none'}],{duration:450,easing:'ease-out'});
  }
  window.Immersive={configure,navbar,hero,works,cards,bottom,bind,refreshCards,enter};
})();
